export default {
  apiGateway: {
    REGION: 'API_GATEWAY_REGION',
    URL: 'API_GATEWAY_URL',
  },
  cognito: {
    REGION: 'AWS_COGNITO_REGION',
    USER_POOL_ID: 'AWS_COGNITO_USER_POOL_ID',
    APP_CLIENT_ID: 'AWS_COGNITO_APP_CLIENT_ID',
    IDENTITY_POOL_ID: 'AWS_COGNITO_IDENTITY_POOL_ID',
  },
};
